
package serviceweb;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MonServiceWeb", targetNamespace = "http://serviceWeb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MonServiceWeb {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "createEntity", targetNamespace = "http://serviceWeb/", className = "serviceweb.CreateEntity")
    @ResponseWrapper(localName = "createEntityResponse", targetNamespace = "http://serviceWeb/", className = "serviceweb.CreateEntityResponse")
    @Action(input = "http://serviceWeb/MonServiceWeb/createEntityRequest", output = "http://serviceWeb/MonServiceWeb/createEntityResponse")
    public void createEntity();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "printStatus", targetNamespace = "http://serviceWeb/", className = "serviceweb.PrintStatus")
    @ResponseWrapper(localName = "printStatusResponse", targetNamespace = "http://serviceWeb/", className = "serviceweb.PrintStatusResponse")
    @Action(input = "http://serviceWeb/MonServiceWeb/printStatusRequest", output = "http://serviceWeb/MonServiceWeb/printStatusResponse")
    public void printStatus();

}
